### ISSUE TITLE
Nodes should sleep, or wait, before trying to join

### ISSUE THREAD

**Issue by tsluyter** [scriptcamp/vagrant-kubeadm-kubernetes#1]
I'm currently adjusting your scripts so they work in my ESXi homelab. 

One thing I've noticed is that the nodes will complete their first stages of setup before the master is ready. This leads to the nodes trying to run "join.sh", which doesn't exist yet because the master hasn't generated it yet. 

Ideally, the nodes should test whether the master is up and running before running "join.sh". Or better yet, simply test whether the file has been created with an until-loop.

Suggestion:
```
echo "Sleeping until K8s master is ready..."
until [[ -s /vagrant/join.sh ]]
do
    sleep 10
done
```

EDIT:
Ah, that might still cause a problem, because the master.sh scripting first creates an empty version of the file before actually putting a config in it. We should also test that the contents are not-null. Only _then_ should the client try to run join.sh. So the test should use "-s", not "-f".

**Comment by bibinwilson** [comment]
@tsluyter but vagrant creates the VM and runs the scripts in the sequential way. so it won't create any issues..

If you have found a solution for ESXi, please raise a PR with a dedicated folder for ESXi

**Comment by tsluyter** [comment]
> @tsluyter vagrant creates the VM and runs the scripts in a sequential way. so it won't create any issues..

When building against ESXi, it doesn't work sequentially. I've seen it build the three VMs in parallel, which causes this easily fixed issue. 

 
> If you have found a solution for ESXi, please raise a PR with a dedicated folder for ESXi

I _do_ have a working solution for ESXi available on my clone of your project -> https://github.com/tsluyter/vagrant-kubeadm-kubernetes 

I will rework my clone according to your suggestion (an ESXi subdir) and I will submit a PR.
