### ISSUE TITLE
Please choose a license for the project

### ISSUE THREAD

**Issue by careyblack** [scriptcamp/vagrant-kubeadm-kubernetes#10]
Reference material for why and how can be found here:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

NOTE:

"
You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.
"

**Comment by scriptcamp** [comment]
@careyblack . Done.. https://github.com/scriptcamp/vagrant-kubeadm-kubernetes/blob/main/LICENSE.md
