### ISSUE TITLE
Issue in calico network and kubernetes dashboard

### ISSUE THREAD

**Issue by haminhsang1903** [scriptcamp/vagrant-kubeadm-kubernetes#2]
![image](https://user-images.githubusercontent.com/64580181/141494756-72f72365-c838-4ffd-a385-aabfebd4af31.png)
I run cmd "vagrant up" and wait for setup success. When I check pods and get errors in above
Info describes pod:
=> Calico controller
![image](https://user-images.githubusercontent.com/64580181/141495419-d814164b-5a69-4c2a-98ce-1f3d3f9df24f.png)
Can you help me with this case! Thank you so much.

**Comment by haminhsang1903** [comment]
I will fix with change id address: 172.16.16.100

**Comment by bibinwilson** [comment]
Thanks @haminhsang1903 for the update..I will add this to README.
