### ISSUE TITLE
swapoff command

### ISSUE THREAD

**Issue by ahmadjubair33** [scriptcamp/vagrant-kubeadm-kubernetes#8]
Hi @bibinwilson  `swapoff -a` command is not working we have to run this command manually.

**Comment by GrapeJuice787** [comment]
Same issue; found a solution [here](https://stackoverflow.com/a/60061820/9699874).

**Comment by scriptcamp** [comment]
Closing it as there is a fix using crontab entry. 

`(crontab -l 2>/dev/null; echo "@reboot /sbin/swapoff -a") | crontab -`
