### ISSUE TITLE
HTTPS error when pulling images from registry.

### ISSUE THREAD

**Issue by GrapeJuice787** [scriptcamp/vagrant-kubeadm-kubernetes#9]
* Verifying image exists in registry with command: `curl $repo/v2/_catalog` results in output:<br> `{"repositories":["simpleapp"]}`
* Output from `kubectl describe pod POD` command below.
<br>
![image](https://user-images.githubusercontent.com/36643484/156789088-9e4ee525-e4de-4f0a-b077-82d279451143.png)

**Comment by scriptcamp** [comment]
Please check your workstation proxy settings.

Closing the issue as it couldn't be reproduced.
